name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (or another version)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Run tests
      - name: Run tests with Maven
        run: mvn test

      # Step 5: Archive the WAR file as an artifact for use in deployment
      - name: Upload WAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: target/*.war

  
